//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamagotchiConsole1.TamaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TamagotchiDTO", Namespace="http://schemas.datacontract.org/2004/07/Tama.Contract")]
    [System.SerializableAttribute()]
    public partial class TamagotchiDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BoredomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CooldownTillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HealthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HungerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAliveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastVisitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SleepField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Boredom {
            get {
                return this.BoredomField;
            }
            set {
                if ((this.BoredomField.Equals(value) != true)) {
                    this.BoredomField = value;
                    this.RaisePropertyChanged("Boredom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CooldownTill {
            get {
                return this.CooldownTillField;
            }
            set {
                if ((this.CooldownTillField.Equals(value) != true)) {
                    this.CooldownTillField = value;
                    this.RaisePropertyChanged("CooldownTill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Health {
            get {
                return this.HealthField;
            }
            set {
                if ((this.HealthField.Equals(value) != true)) {
                    this.HealthField = value;
                    this.RaisePropertyChanged("Health");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hunger {
            get {
                return this.HungerField;
            }
            set {
                if ((this.HungerField.Equals(value) != true)) {
                    this.HungerField = value;
                    this.RaisePropertyChanged("Hunger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAlive {
            get {
                return this.IsAliveField;
            }
            set {
                if ((this.IsAliveField.Equals(value) != true)) {
                    this.IsAliveField = value;
                    this.RaisePropertyChanged("IsAlive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastVisit {
            get {
                return this.LastVisitField;
            }
            set {
                if ((this.LastVisitField.Equals(value) != true)) {
                    this.LastVisitField = value;
                    this.RaisePropertyChanged("LastVisit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sleep {
            get {
                return this.SleepField;
            }
            set {
                if ((this.SleepField.Equals(value) != true)) {
                    this.SleepField = value;
                    this.RaisePropertyChanged("Sleep");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TamagotchiItemDTO", Namespace="http://schemas.datacontract.org/2004/07/Tama.Contract")]
    [System.SerializableAttribute()]
    public partial class TamagotchiItemDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TamaService.ITamagotchiService")]
    public interface ITamagotchiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/GetTamagotchiDTO", ReplyAction="http://tempuri.org/ITamagotchiService/GetTamagotchiDTOResponse")]
        TamagotchiConsole1.TamaService.TamagotchiDTO GetTamagotchiDTO(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/GetTamagotchiDTO", ReplyAction="http://tempuri.org/ITamagotchiService/GetTamagotchiDTOResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> GetTamagotchiDTOAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Rest", ReplyAction="http://tempuri.org/ITamagotchiService/RestResponse")]
        TamagotchiConsole1.TamaService.TamagotchiDTO Rest(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Rest", ReplyAction="http://tempuri.org/ITamagotchiService/RestResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> RestAsync(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Eat", ReplyAction="http://tempuri.org/ITamagotchiService/EatResponse")]
        TamagotchiConsole1.TamaService.TamagotchiDTO Eat(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Eat", ReplyAction="http://tempuri.org/ITamagotchiService/EatResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> EatAsync(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Play", ReplyAction="http://tempuri.org/ITamagotchiService/PlayResponse")]
        TamagotchiConsole1.TamaService.TamagotchiDTO Play(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Play", ReplyAction="http://tempuri.org/ITamagotchiService/PlayResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> PlayAsync(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Workout", ReplyAction="http://tempuri.org/ITamagotchiService/WorkoutResponse")]
        TamagotchiConsole1.TamaService.TamagotchiDTO Workout(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Workout", ReplyAction="http://tempuri.org/ITamagotchiService/WorkoutResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> WorkoutAsync(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Hug", ReplyAction="http://tempuri.org/ITamagotchiService/HugResponse")]
        TamagotchiConsole1.TamaService.TamagotchiDTO Hug(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Hug", ReplyAction="http://tempuri.org/ITamagotchiService/HugResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> HugAsync(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/AddTamagotchi", ReplyAction="http://tempuri.org/ITamagotchiService/AddTamagotchiResponse")]
        TamagotchiConsole1.TamaService.TamagotchiDTO AddTamagotchi(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/AddTamagotchi", ReplyAction="http://tempuri.org/ITamagotchiService/AddTamagotchiResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> AddTamagotchiAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/GetAll", ReplyAction="http://tempuri.org/ITamagotchiService/GetAllResponse")]
        TamagotchiConsole1.TamaService.TamagotchiItemDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/GetAll", ReplyAction="http://tempuri.org/ITamagotchiService/GetAllResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiItemDTO[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITamagotchiServiceChannel : TamagotchiConsole1.TamaService.ITamagotchiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TamagotchiServiceClient : System.ServiceModel.ClientBase<TamagotchiConsole1.TamaService.ITamagotchiService>, TamagotchiConsole1.TamaService.ITamagotchiService {
        
        public TamagotchiServiceClient() {
        }
        
        public TamagotchiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TamagotchiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamagotchiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamagotchiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TamagotchiConsole1.TamaService.TamagotchiDTO GetTamagotchiDTO(int ID) {
            return base.Channel.GetTamagotchiDTO(ID);
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> GetTamagotchiDTOAsync(int ID) {
            return base.Channel.GetTamagotchiDTOAsync(ID);
        }
        
        public TamagotchiConsole1.TamaService.TamagotchiDTO Rest(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi) {
            return base.Channel.Rest(tamagotchi);
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> RestAsync(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi) {
            return base.Channel.RestAsync(tamagotchi);
        }
        
        public TamagotchiConsole1.TamaService.TamagotchiDTO Eat(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi) {
            return base.Channel.Eat(tamagotchi);
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> EatAsync(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi) {
            return base.Channel.EatAsync(tamagotchi);
        }
        
        public TamagotchiConsole1.TamaService.TamagotchiDTO Play(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi) {
            return base.Channel.Play(tamagotchi);
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> PlayAsync(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi) {
            return base.Channel.PlayAsync(tamagotchi);
        }
        
        public TamagotchiConsole1.TamaService.TamagotchiDTO Workout(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi) {
            return base.Channel.Workout(tamagotchi);
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> WorkoutAsync(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi) {
            return base.Channel.WorkoutAsync(tamagotchi);
        }
        
        public TamagotchiConsole1.TamaService.TamagotchiDTO Hug(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi) {
            return base.Channel.Hug(tamagotchi);
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> HugAsync(TamagotchiConsole1.TamaService.TamagotchiDTO tamagotchi) {
            return base.Channel.HugAsync(tamagotchi);
        }
        
        public TamagotchiConsole1.TamaService.TamagotchiDTO AddTamagotchi(string name) {
            return base.Channel.AddTamagotchi(name);
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiDTO> AddTamagotchiAsync(string name) {
            return base.Channel.AddTamagotchiAsync(name);
        }
        
        public TamagotchiConsole1.TamaService.TamagotchiItemDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole1.TamaService.TamagotchiItemDTO[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
