//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamagotchiConsole.TamagotchiClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tamagotchi", Namespace="http://schemas.datacontract.org/2004/07/Tama.Contract")]
    [System.SerializableAttribute()]
    public partial class Tamagotchi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BoredomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HealthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HungerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAliveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastVisitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SleepField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Boredom {
            get {
                return this.BoredomField;
            }
            set {
                if ((this.BoredomField.Equals(value) != true)) {
                    this.BoredomField = value;
                    this.RaisePropertyChanged("Boredom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Health {
            get {
                return this.HealthField;
            }
            set {
                if ((this.HealthField.Equals(value) != true)) {
                    this.HealthField = value;
                    this.RaisePropertyChanged("Health");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hunger {
            get {
                return this.HungerField;
            }
            set {
                if ((this.HungerField.Equals(value) != true)) {
                    this.HungerField = value;
                    this.RaisePropertyChanged("Hunger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAlive {
            get {
                return this.IsAliveField;
            }
            set {
                if ((this.IsAliveField.Equals(value) != true)) {
                    this.IsAliveField = value;
                    this.RaisePropertyChanged("IsAlive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastVisit {
            get {
                return this.LastVisitField;
            }
            set {
                if ((this.LastVisitField.Equals(value) != true)) {
                    this.LastVisitField = value;
                    this.RaisePropertyChanged("LastVisit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sleep {
            get {
                return this.SleepField;
            }
            set {
                if ((this.SleepField.Equals(value) != true)) {
                    this.SleepField = value;
                    this.RaisePropertyChanged("Sleep");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TamagotchiClient.ITamagotchiService")]
    public interface ITamagotchiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/GetTamagotchi", ReplyAction="http://tempuri.org/ITamagotchiService/GetTamagotchiResponse")]
        TamagotchiConsole.TamagotchiClient.Tamagotchi GetTamagotchi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/GetTamagotchi", ReplyAction="http://tempuri.org/ITamagotchiService/GetTamagotchiResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole.TamagotchiClient.Tamagotchi> GetTamagotchiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Sleep", ReplyAction="http://tempuri.org/ITamagotchiService/SleepResponse")]
        TamagotchiConsole.TamagotchiClient.Tamagotchi Sleep();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Sleep", ReplyAction="http://tempuri.org/ITamagotchiService/SleepResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole.TamagotchiClient.Tamagotchi> SleepAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Eat", ReplyAction="http://tempuri.org/ITamagotchiService/EatResponse")]
        TamagotchiConsole.TamagotchiClient.Tamagotchi Eat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Eat", ReplyAction="http://tempuri.org/ITamagotchiService/EatResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole.TamagotchiClient.Tamagotchi> EatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Play", ReplyAction="http://tempuri.org/ITamagotchiService/PlayResponse")]
        TamagotchiConsole.TamagotchiClient.Tamagotchi Play();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Play", ReplyAction="http://tempuri.org/ITamagotchiService/PlayResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole.TamagotchiClient.Tamagotchi> PlayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Workout", ReplyAction="http://tempuri.org/ITamagotchiService/WorkoutResponse")]
        TamagotchiConsole.TamagotchiClient.Tamagotchi Workout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Workout", ReplyAction="http://tempuri.org/ITamagotchiService/WorkoutResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole.TamagotchiClient.Tamagotchi> WorkoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Hug", ReplyAction="http://tempuri.org/ITamagotchiService/HugResponse")]
        TamagotchiConsole.TamagotchiClient.Tamagotchi Hug();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamagotchiService/Hug", ReplyAction="http://tempuri.org/ITamagotchiService/HugResponse")]
        System.Threading.Tasks.Task<TamagotchiConsole.TamagotchiClient.Tamagotchi> HugAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITamagotchiServiceChannel : TamagotchiConsole.TamagotchiClient.ITamagotchiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TamagotchiServiceClient : System.ServiceModel.ClientBase<TamagotchiConsole.TamagotchiClient.ITamagotchiService>, TamagotchiConsole.TamagotchiClient.ITamagotchiService {
        
        public TamagotchiServiceClient() {
        }
        
        public TamagotchiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TamagotchiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamagotchiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamagotchiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TamagotchiConsole.TamagotchiClient.Tamagotchi GetTamagotchi() {
            return base.Channel.GetTamagotchi();
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole.TamagotchiClient.Tamagotchi> GetTamagotchiAsync() {
            return base.Channel.GetTamagotchiAsync();
        }
        
        public TamagotchiConsole.TamagotchiClient.Tamagotchi Sleep() {
            return base.Channel.Sleep();
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole.TamagotchiClient.Tamagotchi> SleepAsync() {
            return base.Channel.SleepAsync();
        }
        
        public TamagotchiConsole.TamagotchiClient.Tamagotchi Eat() {
            return base.Channel.Eat();
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole.TamagotchiClient.Tamagotchi> EatAsync() {
            return base.Channel.EatAsync();
        }
        
        public TamagotchiConsole.TamagotchiClient.Tamagotchi Play() {
            return base.Channel.Play();
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole.TamagotchiClient.Tamagotchi> PlayAsync() {
            return base.Channel.PlayAsync();
        }
        
        public TamagotchiConsole.TamagotchiClient.Tamagotchi Workout() {
            return base.Channel.Workout();
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole.TamagotchiClient.Tamagotchi> WorkoutAsync() {
            return base.Channel.WorkoutAsync();
        }
        
        public TamagotchiConsole.TamagotchiClient.Tamagotchi Hug() {
            return base.Channel.Hug();
        }
        
        public System.Threading.Tasks.Task<TamagotchiConsole.TamagotchiClient.Tamagotchi> HugAsync() {
            return base.Channel.HugAsync();
        }
    }
}
